### ISSUE TITLE
Gmail login error

### ISSUE THREAD

**Issue by JensenWD** [FIU-SCIS-Senior-Projects/VIP3#2]
Attempting to sign in via Gmail (I used a non fiu.edu account) leads me to a token error page. Picture attached. 
<img width="1280" alt="screen shot 2016-06-14 at 7 19 21 pm" src="https://cloud.githubusercontent.com/assets/19538564/16063022/15641164-3265-11e6-8947-36fc6ad4fcaa.png">

**Comment by dlope073** [comment]
The issue has been fixed, I can never replicate it on my end so please check on your end. Remember only FIU.EDU can work with Gmail login not Gmail.
