### ISSUE TITLE
userRoutes.js - Line 14 not returning proper host

### ISSUE THREAD

**Issue by JensenWD** [FIU-SCIS-Senior-Projects/VIP3#3]
Line 14 has had a temp fix, needs to be revisited for a proper fix. Ask vlad for replication steps.

**Comment by dlope073** [comment]
I don't understand the line just prints the host for debugging. It is definetly printing the write host. By the way you have to have change the host in server.js

**Comment by dlope073** [comment]
The variable  host is stored in the server.js file.

**Comment by dlope073** [comment]
Closing this as this isn't an issue. The server.js file is where the host variable is stored.
