### ISSUE TITLE
Student should have access while waiting for PI approval

### ISSUE THREAD

**Issue by JensenWD** [FIU-SCIS-Senior-Projects/VIP3#5]
Whenever a student signs up via Gmail, "piApproval" is set to false in the database and the student cant do anything

**Comment by dlope073** [comment]
Um it sets it to false but it can login in just fine. Are you certain you can't log into Gmail. Remember it must be an FIU.EDU for it to work. If not you cannot login into the system.

**Comment by dlope073** [comment]
I am closing this as it isn't an issue. I am guessing Johny you must be logged in as a FIU.EDU
